name: Build iPSX2 iOS
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Download MoltenVK
        run: |
          curl -L https://github.com/KhronosGroup/MoltenVK/releases/download/v1.4.1/MoltenVK-ios.tar -o MoltenVK.tar
      - name: Extract MoltenVK
        run: |
          tar -xf MoltenVK.tar
      - name: Create Frameworks directory
        run: |
          mkdir -p Frameworks
      - name: Move MoltenVK framework
        run: |
          find . -path "*/ios-arm64/MoltenVK.framework" -exec cp -R {} ./Frameworks/ \;
      - name: Verify Frameworks
        run: |
          ls -R $GITHUB_WORKSPACE/Frameworks
      - name: CMake Configure
        run: |
          cmake -B build -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_FRAMEWORK_PATH=$GITHUB_WORKSPACE/Frameworks -DMoltenVK_FRAMEWORK_PATH=$GITHUB_WORKSPACE/Frameworks/MoltenVK.framework
      - name: Build
        run: |
          cmake --build build --config Release --target iPSX2
